title: Em đứng đây từ chiều　夕からこれで立っていた
theme: minima
author: Keit
email: nxtkiet612@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ngày mai em đi
  Còn nhớ
  Tháng ngày trôi qua
  Thầm lặng
  Anh biết không

# social links
twitter_username: kittehUWU # DO NOT include the @ character, or else the build will fail!
github_username:  keitng # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
